### ISSUE TITLE
warnning

### ISSUE THREAD

**Issue by Faiaz99** [ijs-f8/Research-Reactor-Simulator#4]
![هسسع](https://user-images.githubusercontent.com/109645231/179913418-7dbf8f57-4d62-4de4-ad42-c75b95c96454.PNG)
![هسسع](https://user-images.githubusercontent.com/109645231/179913474-275e6fb4-8a44-4f8f-946d-8b7cbab212cc.PNG)

**Comment by janmalec** [comment]
Hello! Could you please post the output of the error that you get in the window below?

**Comment by janmalec** [comment]
Not enough info was provided. Will reopen if necessary.
